version: '3'
services:
  app:
    build: .
    ports:
      - "7860:7860"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - TRANSFORMERS_CACHE=/code/.cache/huggingface
      - HF_HOME=/code/.cache/huggingface
      - MPLCONFIGDIR=/code/.config/matplotlib
      - PADDLE_HOME=/code/.paddleocr
      - HOME=/code
      - TMPDIR=/code/tmp
      - PYTHONPATH=/code
    volumes:
      - .:/code
      - cache_data:/code/.cache
      - config_data:/code/.config
      - paddle_data:/code/.paddleocr
      - tmp_data:/code/tmp
      - uploaded_files:/code/uploaded_files
      - extracted_images:/code/extracted_images
    user: "1000:1000"
    networks:
      - supabase_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  supabase_network:
    external: true
    name: supabase_default

volumes:
  cache_data:
  config_data:
  paddle_data:
  tmp_data:
  uploaded_files:
  extracted_images: